packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  "@central-icons-svelte/round-outlined-radius-2-stroke-1.5": true
  better-sqlite3: true
  esbuild: true

minimumReleaseAgeExclude:
  - "@tauri-apps/plugin-clipboard-manager@2.3.3"

overrides:
  undici: 6.28.0
