export { createHost } from "./create-host.js";
export {
  HostError,
  isHostError,
  isWattBoundaryError,
  type WattBoundaryError,
} from "./errors.js";
export type {
  CreateHostOptions,
  Host,
  HostEvent,
  HostCapabilities,
  ModelCatalogState,
  Project,
  ProjectReconciliation,
  ReconciliationEntry,
  Run,
  RunError,
  RunResult,
  RunStatus,
  Session,
  Workspace,
  WorkspaceOperation,
  WorkspaceOperationBranchOutcome,
  WorkspaceOperationCompensationOutcome,
  WorkspaceOperationDiagnostic,
  WorkspaceOperationPhase,
  WorkspaceOperationTerminalOutcome,
  WorkspaceOperationType,
} from "./types.js";
