import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { test } from "node:test";

import { evaluateReleaseGate, pendingChangesetFiles } from "./release-gate.mjs";
import { syncReleaseVersion } from "./sync-release-version.mjs";

test("pendingChangesetFiles ignores config and README", () => {
  assert.deepEqual(pendingChangesetFiles(["config.json", "README.md", "curly-wolves-remain.md"]), [
    "curly-wolves-remain.md",
  ]);
});

test("release gate packages only a version bump without leftover changesets", () => {
  const versioned = evaluateReleaseGate({
    hasChangesets: false,
    pendingChangesets: [],
    tagExists: false,
    changedFiles: ["packages/cli/package.json", "packages/cli/CHANGELOG.md"],
    version: "0.1.0",
  });
  assert.deepEqual(versioned, {
    shouldPackage: true,
    tag: "v0.1.0",
    version: "0.1.0",
  });

  assert.equal(
    evaluateReleaseGate({
      hasChangesets: true,
      pendingChangesets: [],
      tagExists: false,
      changedFiles: ["packages/cli/package.json"],
      version: "0.1.0",
    }).shouldPackage,
    false,
  );
  assert.equal(
    evaluateReleaseGate({
      hasChangesets: false,
      pendingChangesets: ["blue-foxes-sing.md"],
      tagExists: false,
      changedFiles: ["packages/cli/package.json"],
      version: "0.1.0",
    }).shouldPackage,
    false,
  );
  assert.equal(
    evaluateReleaseGate({
      hasChangesets: false,
      pendingChangesets: [],
      tagExists: true,
      changedFiles: ["packages/cli/package.json"],
      version: "0.1.0",
    }).shouldPackage,
    false,
  );
  assert.equal(
    evaluateReleaseGate({
      hasChangesets: false,
      pendingChangesets: [],
      tagExists: false,
      changedFiles: ["README.md"],
      version: "0.0.1",
    }).shouldPackage,
    false,
  );
});

test("syncReleaseVersion copies the product version into root and Cargo manifests", () => {
  const repo = mkdtempSync(path.join(tmpdir(), "watt-release-sync-"));
  mkdirSync(path.join(repo, "packages", "cli"), { recursive: true });
  mkdirSync(path.join(repo, "apps", "desktop", "src-tauri"), {
    recursive: true,
  });
  writeFileSync(
    path.join(repo, "packages", "cli", "package.json"),
    `${JSON.stringify({ name: "@watt/cli", version: "0.2.0" }, null, 2)}\n`,
  );
  writeFileSync(
    path.join(repo, "package.json"),
    `${JSON.stringify({ name: "watt", version: "0.0.1" }, null, 2)}\n`,
  );
  writeFileSync(
    path.join(repo, "apps", "desktop", "package.json"),
    `${JSON.stringify({ name: "@watt/desktop", version: "0.0.1" }, null, 2)}\n`,
  );
  writeFileSync(
    path.join(repo, "apps", "desktop", "src-tauri", "Cargo.toml"),
    `[package]\nname = "watt-desktop"\nversion = "0.0.1"\nedition = "2024"\n`,
  );
  writeFileSync(
    path.join(repo, "apps", "desktop", "src-tauri", "Cargo.lock"),
    `# This file is automatically @generated by Cargo.\n[[package]]\nname = "watt-desktop"\nversion = "0.0.1"\n`,
  );

  assert.equal(syncReleaseVersion(repo), "0.2.0");
  assert.equal(JSON.parse(readFileSync(path.join(repo, "package.json"), "utf8")).version, "0.2.0");
  assert.equal(
    JSON.parse(readFileSync(path.join(repo, "apps", "desktop", "package.json"), "utf8")).version,
    "0.2.0",
  );
  assert.match(
    readFileSync(path.join(repo, "apps", "desktop", "src-tauri", "Cargo.toml"), "utf8"),
    /name = "watt-desktop"\nversion = "0.2.0"/,
  );
  assert.match(
    readFileSync(path.join(repo, "apps", "desktop", "src-tauri", "Cargo.lock"), "utf8"),
    /name = "watt-desktop"\nversion = "0.2.0"/,
  );
});
